# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upterm < Formula
  desc ""
  homepage ""
  version "0.6.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/owenthereal/upterm/releases/download/v0.6.2/upterm_darwin_amd64.tar.gz"
    sha256 "3bceb5485909e709abd9718d15556248c8e85ced6ce00667ad8095b351ad2db5"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/owenthereal/upterm/releases/download/v0.6.2/upterm_darwin_arm64.tar.gz"
    sha256 "a4a4d885796e51c5a18a7a03462acd3b648933953f251d223b7d42e304f9f814"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/owenthereal/upterm/releases/download/v0.6.2/upterm_linux_amd64.tar.gz"
    sha256 "286cd74c26dc50a023a27d2e32ba739c7b40f203e900904ab6604e14e920d2df"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/owenthereal/upterm/releases/download/v0.6.2/upterm_linux_arm64.tar.gz"
    sha256 "f94ca97211792b0b2de00d8ece87456f578989db438e1c86eca3488b71d02780"
  end

  def install
    bin.install "upterm"
    prefix.install_metafiles
    bash_completion.install "etc/completion/upterm.bash_completion.sh"
    zsh_completion.install "etc/completion/upterm.zsh_completion" => "_upterm"
    man.install "etc/man/man1"
  end

  test do
    assert_match(/Upterm version/, shell_output("#{bin}/upterm version"))
  end
end
