# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upterm < Formula
  desc "Secure terminal sharing"
  homepage "https://upterm.dev"
  version "0.6.4"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/owenthereal/upterm/releases/download/v0.6.4/upterm_darwin_amd64.tar.gz"
    sha256 "94e9a4d239d7567a191b18167ee85228478390809905345d2561f3a90a1c1f08"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/owenthereal/upterm/releases/download/v0.6.4/upterm_darwin_arm64.tar.gz"
    sha256 "6d4559968a3eb77ba27e2212188ebde014a30ecba4070908aeae657a482e37af"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/owenthereal/upterm/releases/download/v0.6.4/upterm_linux_amd64.tar.gz"
    sha256 "5a1871dc234ea94c890741e1bab88c8982ba6b7881b11afbf4b91e701509f199"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/owenthereal/upterm/releases/download/v0.6.4/upterm_linux_arm64.tar.gz"
    sha256 "4824eea3ceccaff5029fecf6ce50bab7d2b2b17c3a73eea6d9ee5eb0083414cc"
  end

  head "https://github.com/owenthereal/upterm.git"

  def install
    bin.install "upterm"
    prefix.install_metafiles
    bash_completion.install "etc/completion/upterm.bash_completion.sh"
    zsh_completion.install "etc/completion/upterm.zsh_completion" => "_upterm"
    man.install "etc/man/man1"
  end

  test do
    assert_match(/Upterm version/, shell_output("#{bin}/upterm version"))
  end
end
