# This file was generated by GoReleaser. DO NOT EDIT.
cask "upterm" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/upterm"]
    end
  end

  version "0.32.0"

  on_macos do
    on_arm do
      sha256 "71e383d91c4b51677ee453a10e12b99a01ef452499d6db7828a979907178a78e"
      url "https://github.com/owenthereal/upterm/releases/download/v#{version}/upterm_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cf7ac46028f82d173f207f4cfc3eb8e7fe565ef54b2070c678b5be5d7a167293"
      url "https://github.com/owenthereal/upterm/releases/download/v#{version}/upterm_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7c2f6d89ce97bdd9a2fb405c4c48235ea78a77b2d6e621fc909d7aaab3764090"
      url "https://github.com/owenthereal/upterm/releases/download/v#{version}/upterm_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4b70494aacb8d22dec35dd5210fd741bb4c7647520458766e36a29c189993739"
      url "https://github.com/owenthereal/upterm/releases/download/v#{version}/upterm_linux_amd64.tar.gz"
    end
  end

  name "upterm"
  desc "Instant Terminal Sharing"
  homepage "https://upterm.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "upterm"
  manpage "etc/man/man1/upterm-host.1"
  manpage "etc/man/man1/upterm-proxy.1"
  manpage "etc/man/man1/upterm-session-current.1"
  manpage "etc/man/man1/upterm-session-info.1"
  manpage "etc/man/man1/upterm-session-list.1"
  manpage "etc/man/man1/upterm-session.1"
  manpage "etc/man/man1/upterm-upgrade.1"
  manpage "etc/man/man1/upterm-version.1"
  manpage "etc/man/man1/upterm.1"
  bash_completion "etc/completion/upterm.bash_completion.sh"
  zsh_completion "etc/completion/upterm.zsh_completion"

  # No zap stanza required
end
