# This file was generated by GoReleaser. DO NOT EDIT.
cask "upterm" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/upterm"]
    end
  end

  version "0.29.0"

  on_macos do
    on_arm do
      sha256 "229cb90a2678673ea6bd5a1c32b61fc2bda453edd1c45fed39f016c730dd40d2"
      url "https://github.com/owenthereal/upterm/releases/download/v#{version}/upterm_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b0e721352f228eb66aebad32a63f60ada9b2e73a68529da1efbf915b7fa2b4aa"
      url "https://github.com/owenthereal/upterm/releases/download/v#{version}/upterm_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b7844b90e2714c8549d9cb88f4d870af51411e531a13d6dd84f6457888bdfeae"
      url "https://github.com/owenthereal/upterm/releases/download/v#{version}/upterm_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6e88b9101808f1d47d4a3100a757d6b35f75e21ce0925535a08653a8458b70d7"
      url "https://github.com/owenthereal/upterm/releases/download/v#{version}/upterm_linux_amd64.tar.gz"
    end
  end

  name "upterm"
  desc "Instant Terminal Sharing"
  homepage "https://upterm.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "upterm"
  manpage "etc/man/man1/upterm-host.1"
  manpage "etc/man/man1/upterm-proxy.1"
  manpage "etc/man/man1/upterm-session-current.1"
  manpage "etc/man/man1/upterm-session-info.1"
  manpage "etc/man/man1/upterm-session-list.1"
  manpage "etc/man/man1/upterm-session.1"
  manpage "etc/man/man1/upterm-upgrade.1"
  manpage "etc/man/man1/upterm-version.1"
  manpage "etc/man/man1/upterm.1"
  bash_completion "etc/completion/upterm.bash_completion.sh"
  zsh_completion "etc/completion/upterm.zsh_completion"

  # No zap stanza required
end
