# This file was generated by GoReleaser. DO NOT EDIT.
cask "upterm" do
  name "upterm"
  desc "Instant Terminal Sharing"
  homepage "https://upterm.dev"
  version "0.21.1-dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "upterm"
  manpage "etc/man/man1/upterm.1"
  manpage "etc/man/man1/upterm-host.1"
  manpage "etc/man/man1/upterm-proxy.1"
  manpage "etc/man/man1/upterm-session.1"
  manpage "etc/man/man1/upterm-session-current.1"
  manpage "etc/man/man1/upterm-session-info.1"
  manpage "etc/man/man1/upterm-session-list.1"
  manpage "etc/man/man1/upterm-upgrade.1"
  manpage "etc/man/man1/upterm-version.1"
  bash_completion "etc/completion/upterm.bash_completion.sh"
  zsh_completion "etc/completion/upterm.zsh_completion"

  on_macos do
    on_intel do
      url "https://github.com/owenthereal/upterm/releases/download/v#{version}/upterm_darwin_amd64.tar.gz"
      sha256 "252cc511945c3e30df05532d0085fd862cd7c16759273c14cbe0d1122e2a14ea"
    end
    on_arm do
      url "https://github.com/owenthereal/upterm/releases/download/v#{version}/upterm_darwin_arm64.tar.gz"
      sha256 "8488aa2310de71e03d1072a1f9931bb645e74d62537fb532c1ffefab0dde8af9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/owenthereal/upterm/releases/download/v#{version}/upterm_linux_amd64.tar.gz"
      sha256 "f1b9d53db7f6995cd74ec04b55788404c136b144b40b7350da807ca2298b3551"
    end
    on_arm do
      url "https://github.com/owenthereal/upterm/releases/download/v#{version}/upterm_linux_arm64.tar.gz"
      sha256 "5103578e29de9c23b494ec997006d7746460edf9e36ca84967ffce2d357825e8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/upterm"]
    end
  end

  # No zap stanza required
end
