# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upterm < Formula
  desc "Secure terminal sharing"
  homepage "https://upterm.dev"
  version "0.6.3"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/owenthereal/upterm/releases/download/v0.6.3/upterm_darwin_amd64.tar.gz"
    sha256 "8dbb6228d4a8b6cf0b2ca3b8936adbfefed895c2d6622c9e2a5a461df047d9e8"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/owenthereal/upterm/releases/download/v0.6.3/upterm_darwin_arm64.tar.gz"
    sha256 "0d2227dbea4c489f567e3916b672be52496e87d43b4e145cd00b8c82ade41c6b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/owenthereal/upterm/releases/download/v0.6.3/upterm_linux_amd64.tar.gz"
    sha256 "cd3385f10fdf81c0605776ef82c462018bfc94f4f14bd5a0fcf419b5d6d879e4"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/owenthereal/upterm/releases/download/v0.6.3/upterm_linux_arm64.tar.gz"
    sha256 "99c780b876875c39b922b971a8dc50411c4d7f9ca1cc0fd4eca694a63df0af64"
  end

  head "https://github.com/owenthereal/upterm.git"

  def install
    bin.install "upterm"
    prefix.install_metafiles
    bash_completion.install "etc/completion/upterm.bash_completion.sh"
    zsh_completion.install "etc/completion/upterm.zsh_completion" => "_upterm"
    man.install "etc/man/man1"
  end

  test do
    assert_match(/Upterm version/, shell_output("#{bin}/upterm version"))
  end
end
