# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upterm < Formula
  desc "Secure terminal sharing"
  homepage "https://upterm.dev"
  version "0.8.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/owenthereal/upterm/releases/download/v0.8.1/upterm_darwin_amd64.tar.gz"
      sha256 "2dda72ff6c8cacab8f28161b80c313ec7dfdeac28eebd301b7c410e1d80ba8ae"

      def install
        bin.install "upterm"
        prefix.install_metafiles
        bash_completion.install "etc/completion/upterm.bash_completion.sh"
        zsh_completion.install "etc/completion/upterm.zsh_completion" => "_upterm"
        man.install "etc/man/man1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/owenthereal/upterm/releases/download/v0.8.1/upterm_darwin_arm64.tar.gz"
      sha256 "4527b113767a480579c9c2649c59d62c41828ff3fcfc5ee28f06b383b1fad4e6"

      def install
        bin.install "upterm"
        prefix.install_metafiles
        bash_completion.install "etc/completion/upterm.bash_completion.sh"
        zsh_completion.install "etc/completion/upterm.zsh_completion" => "_upterm"
        man.install "etc/man/man1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/owenthereal/upterm/releases/download/v0.8.1/upterm_linux_amd64.tar.gz"
      sha256 "159de310c2c7ed30e2de3688b1492f68884a5b606cd8aa49b54db5bfeb492c39"

      def install
        bin.install "upterm"
        prefix.install_metafiles
        bash_completion.install "etc/completion/upterm.bash_completion.sh"
        zsh_completion.install "etc/completion/upterm.zsh_completion" => "_upterm"
        man.install "etc/man/man1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/owenthereal/upterm/releases/download/v0.8.1/upterm_linux_arm64.tar.gz"
      sha256 "cc33d37cad2f6d2576ebbc272051a2911fdb9415b016eaa51aecc7ec8e431bef"

      def install
        bin.install "upterm"
        prefix.install_metafiles
        bash_completion.install "etc/completion/upterm.bash_completion.sh"
        zsh_completion.install "etc/completion/upterm.zsh_completion" => "_upterm"
        man.install "etc/man/man1"
      end
    end
  end

  head "https://github.com/owenthereal/upterm.git"

  test do
    assert_match(/Upterm version/, shell_output("#{bin}/upterm version"))
  end
end
